### GENERAL SETTINGS ###

# Site settings
title: CA-935th - Scripps Ranch HS AFJROTC
description: "Welcome to the page for the Scripps Ranch High School AFJROTC. CA-935th.com is run by cadets in our program and serves to showcase our events, 
cadets, and information about our corps."
baseurl: ""
url: "http://ca-935th.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
    limit: 9

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: https://github.com/CA-935
  - title: facebook
    url: https://www.facebook.com/srhspublicaffairs
  - title: snapchat-ghost
    url: https://www.snapchat.com/add/srhspa
  - title: youtube-play
    url: https://www.youtube.com/channel/UC13o8MjH8SXrb1QIAHcCEdA
  - title: instagram
    url: https://www.instagram.com/ca.935th

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - 10410 Treena Street
    - San Diego, CA 92131
#email: 
#tel: it's in the contact us page so dont put it here


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
#members:
#  - name: Mark Webber
#    position: CEO
#    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
#    img: team01.jpg
#    social:
#      - title: envelope #use for email address
#        url: mailto:name@domain.com
#      - title: twitter
#        url: http://twitter.com/handle

members:
  - name: Johanna Kye 
    position: Public Affairs Officer
    img: Johanna.JPG
    social:
      - title: facebook  
        url: https://www.facebook.com/johana.kye
  - name: EJ Buan
    position: Public Affairs NCO
    img: EJ.jpg
    social:
      - title: facebook  
        url: https://www.facebook.com/ej.buan?fb_dtsg_ag=AdxOnC_ugAdEi-t1xFPC2Ipo6GoLPHZTUe2ExGvebXKyFg%3AAdwQHK01F_U-ZTHY8cYmwBPq-InRQIyk_nqke6qMw8lDzQ
  - name: Kyrstn Hall
    position: Public Affairs NCO
    img: pa.jpg
    social:
      - title: facebook  
        url: https://www.facebook.com/asiandallas?fb_dtsg_ag=AdxOnC_ugAdEi-t1xFPC2Ipo6GoLPHZTUe2ExGvebXKyFg%3AAdwQHK01F_U-ZTHY8cYmwBPq-InRQIyk_nqke6qMw8lDzQ
  - name: Mitchell Le
    position: Technology Officer
    img: CC TECH.jpg
  - name: Eric Kye
    position: Technology NCO
  - name: Justin Bui
    position: Technology NCO
    img: justin.jpg
    
    
alphamembers:
- name: Dylan Tran
   position: Alpha Flight Commander
   img: alphaCC.jpg
- name: Samantha Scothlas
   position: Alpha Flight Sergeant
   img: alphaSGT.jpg
   
bravomembers:
- name: Michelle Resubal
   position: Bravo Flight Commander
   img: bravoCC.jpg
- name: Aland Sinjari
   position: Bravo Flight Sergeant
   img: bravoSGT.jpg
    
charliemembers:
- name: Matthew Custodio
   position: Charlie Flight Commander
   img: charlieCC.jpg
- name: Katherine Tat
   position: Charlie Flight Sergeant
   img: charlieSGT.jpg
    
deltamembers:
- name: Brandy Opondo
   position: Delta Flight Commander
   img: deltaCC.jpg
- name: Phillip Sargent
   position: Delta Flight Sergeant
   img: deltaSGT.jpg
    
echomembers:
- name: Aish Kirawant
   position: Echo Flight Commander
   img: echoCC.jpg
- name: Christian Yoon
   position: Echo Flight Sergeant
   img: echoSGT.jpg    

foxtrotmembers:
- name: Athena Amanatidis
   position: Foxtrot Flight Commander
   img: foxtrotCC.jpg
- name: Nyssa Sais Montoya
   position: Foxtrot Flight Sergeant
   img: foxtrotSGT.jpg
    
golfmembers:
- name: Thomas Phan
   position: Golf Flight Commander
   img: golfCC.jpg
- name: Xavier dela Cruz
   position: Golf Flight Sergeant

    
    

armedmembers:
  - name: Matthew Custodio
    position: Armed Team Commander
    img: charlieCC.jpg
  - name: Thomas Phan
    position: Armed Team NCO
    img: golfCC.jpg

cgmembers:
  - name: Christina O
    position: Color Guard Commander
    img: cgCC.jpg
  - name: Derek Phan
    position: Color Guard NCO


flagdetailmembers:
  - name: Phoebe Lam
    img: CC Flag Detail.jpg
    position: Flag Detail Commander
  - name: Walter de Lorrell
    position: Flag Detail NCO


sabermembers:
  - name: Nick Stone 
    position: Saber Team Commander
    img: Nick.JPG
  - name: Jeremy Doan
    position: Saber Team NCO
    img: sabersgt.jpg

unarmedmembers:
  - name: Johanna Kye
    position: Unarmed Team Commander
    img: Johanna.JPG
  - name: Brianna Ly
    position: Unarmed Team NCO


academicmembers:
  - name: Raymond Sun
    position: Academic Team NCO
    img: academic.jpg
  
kittyhawkmembers:
  - name: Athena Amanatidis
    position: Kitty Hawk Officer
  - name: Tina Ton
    position: Kitty Hawk NCO
  - name: Trent Bien
    position: Kitty Hawk NCO

staffmembers:
  - name: Valerie Ho
    position: Group Commander
    img: valerie.jpg
    social:
      - title: facebook
        url: https://www.facebook.com/profile.php?id=100004596104814
  - name: Brandon Nguyen
    position: Deputy Commander
    img: brandon.jpg
  - name: Chloe Dietrich
    position: First Sergeant
    img: chloe.jpg
    social:
      - title: facebook 
        url: https://www.facebook.com/chloe.dietrich.1
  - name: Evan Dicker
    position: Operations Commander
    img: evan.jpg
    social:
      - title: facebook 
        url: https://www.facebook.com/evan.dicker.47371
  - name: Nick Stone
    position: Teams Commander
    img: nick.jpg
    social:
      - title: facebook 
        url: https://www.facebook.com/profile.php?id=100004798337733
  - name: Shane Donahue
    position: Mission Support Commander
    img: shane.jpg
    social:
      - title: facebook 
        url: https://www.facebook.com/profile.php?id=100010223324308
  - name: Lindsey Trinh 
    position: Plans and Programs
    img: lindsey.jpg
    social:
      - title: facebook 
        url: https://www.facebook.com/lindsey.trinh.3
  - name: Christine Nguyen
    position: Logistics Commander 
    img: christine.jpg
    social:
      - title: facebook 
        url: https://www.facebook.com/profile.php?id=100005976706220
  - name: Johanna Kye
    position: Public Affairs Commander
    img: johanna.jpg
    social:
      - title: facebook  
        url: https://www.facebook.com/johana.kye

ypfmembers:
  - name: TBA
    position: YPF Captain
    img: placeholder.jpg
  - name: TBA
    position: YPF Co-Captain
    img: placeholder.jpg

aptmembers:
  - name: Lynn Lu
    position: APT Commander
    img: CC APT.jpg
  - name: Nyssa Sais Montoya
    position: APT NCO
    img: SGT APT.jpg

cyberpatriotmembers:
  - name: Alex Roh
    position: CyberPatriot Commander
    img: cpcc.jpg
  - name: Darius Yeung
    position: CyberPatriot NCO
    img: SGT CP.jpg

# Clients information. Shown on Home and About pages.
sponsors:
  - name: iD Tech
    img: sponsor1.svg

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Scripps Ranch High School’s Air Force Junior Reserve Officer Training Corps (AFJROTC) CA-935th program has been the number 
one JROTC unit in the San Diego Unified School District for many years. We value hard-work, friendship, and achievement, pushing our 
cadets not only to be their best, but also to perform their best."

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "It's not what you have or what you know; it's what you do with your talent, skills, knowledge, and education that will determine your perfomance and give you the competitive edge!"
    author: MSgt. Toledo
    position: Aerospace Science Instructor - SRHS AFJROTC

prose:
  rooturl: '_posts'
  siteurl: 'https://ca-935.github.io'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "tag1"
              value: "tag1"
            - name: "tag2s"
              value: "tag2"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
