### GENERAL SETTINGS ###

# Site settings
title: CA-935th - Scripps Ranch HS AFJROTC
description: "Welcome to the page for the Scripps Ranch High School AFJROTC. CA-935th.com is run by cadets in our program and serves to showcase our events, 
cadets, and information about our corps."
baseurl: ""
url: "http://ca-935th.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
    limit: 9

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: https://github.com/CA-935
  - title: facebook
    url: https://www.facebook.com/srhspublicaffairs
  - title: snapchat-ghost
    url: https://www.snapchat.com/add/srhspa
  - title: youtube-play
    url: https://www.youtube.com/channel/UC13o8MjH8SXrb1QIAHcCEdA
  - title: instagram
    url: https://www.instagram.com/ca.935th

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - 10410 Treena Street
    - San Diego, CA 92131
#email: 
#tel: it's in the contact us page so dont put it here


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
#members:
#  - name: Mark Webber
#    position: CEO
#    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
#    img: team01.jpg
#    social:
#      - title: envelope #use for email address
#        url: mailto:name@domain.com
#      - title: twitter
#        url: http://twitter.com/handle

members:
  - name: Justin Bui
    position: Public Affairs Officer
    img: Bui, Justin 20202021.png
    
 
  - name: Khushi Chaudhari
    position: Public Affairs NCO
    img: Chaudhari, Khushi 20202021.png
  
  - name: Sanjana Santhosh
    position: Public Affairs NCO
    img: Santhosh, Sanjana 20202021.png
    
  - name: Johann Welch
    position: Technology Officer
    img: Welch, Johann 20202021.png
    
  - name: Sahithi Lingampalli
    position: Technology NCO
    img: Lingampalli, Sahithi 20202021.png

  - name: Keshav Srinivasan
    position: Technology NCO
    img: Srinivasan, Keshav 20202021.png
    
    
alphamembers:
  - name: Abel Hurtado
    position: Alpha Flight Commander
    img: Hurtado, Abel 20202021.JPG
    social:
      - title: envelope
        url: mailto:abelhurt13@gmail.com
  - name: Pahel Srivastava
    position: Alpha Flight Sergeant
    img: Srivastava, Pahel 20202021.jpg
    social:
      - title: envelope
        url: mailto:pahel.srivastava@gmail.com
   
bravomembers:
  - name: Marcus Velasquez
    position: Bravo Flight Commander
    img: Velazquez, Marcus 20202021.JPG
    social:
      - title: envelope
        url: mailto:marcusvelasquez132@gmail.com
  - name: Haleigh Quinn
    position: Bravo Flight Sergeant
    img: Quinn, Haleigh  20202021.JPG
    social:
      - title: envelope
        url: mailto:hkquinn4@gmail.com
    
charliemembers:
  - name: EJ Buan
    position: Charlie Flight Commander
    img: Buan, EJ 20202021.JPG
    social:
      - title: envelope
        url: mailto:ejeffeljohbuan24@gmail.com
  - name: Jessica Pham
    position: Charlie Flight Sergeant
    img: Pham, Jessica 20202021.jpg
    social:
      - title: envelope
        url: mailto:jphamca@yahoo.com

    
deltamembers:
  - name: Joshua Pagaduan
    position: Delta Flight Commander
    img: Pagaduan, Joshua 20202021.JPG
    social:
      - title: envelope
        url: mailto:j3pag280@gmail.com
  - name: Hilary Nguyen
    position: Delta Flight Sergeant
    img: Nguyen, Hilary 20202021.PNG
    social:
      - title: envelope
        url: mailto:hi.04.nguyen@gmail.com
    
echomembers:
  - name: Justin Nguyen
    position: Echo Flight Commander
    img: Nguyen, Justin 20202021.jpg
    social:
      - title: envelope
        url: mailto:jusnguyen1@gmail.com
  - name: Michael He
    position: Echo Flight Sergeant
    img: He, Michael 20202021.JPG
    social:
      - title: envelope
        url: mailto:michaelhe2016@gmail.com  

foxtrotmembers:
  - name: Christina Nguyen
    position: Foxtrot Flight Commander
    img: Nguyen, Christina 20202021.JPG
    social:
      - title: envelope
        url: mailto:christinan2004@gmail.com
  - name: Lucky Hong
    position: Foxtrot Flight Sergeant
    img: Hong, Lucky 20202021.PNG
    social:
       - title: envelope
         url: mailto:luckyhonglol@gmail.com

golfmembers:
  - name: Ryan Ong
    position: Golf Flight Commander
    img: golfcc1920.jpg
  - name: Rusell Lee
    position: Golf Flight Sergeant
    img: golfsgt1920.jpg

hotelmembers:
  - name: David Udom
    position: Hotel Flight Commander
    img: Udom, David.jpg
  - name: Tom Rufino
    position: Hotel Flight Sergeant
    img: Rufino, Tom.jpg
    
    

armedmembers:
  - name: Tom Rufino
    position: Armed Team Commander
    img: Rufino, Tom 20202021.png
  - name: Xavier Rico
    position: Armed Team NCO
    img: Rico, Xavier 20202021.png

cgmembers:
  - name: Elijah Bautista
    position: Color Guard Commander
    img: Bautista, Elijah 20202021.png
  - name: Ethan Ramirez
    position: Color Guard NCO
    img: Ramirez, Ethan 20202021.png


flagdetailmembers:
  - name: Eric Kye
    img: Kye, Eric 20202021.png
    position: Flag Detail Commander
  - name: Lea Chanthaluxay
    position: Flag Detail NCO
    img: Chanthaluxay, Lea 20202021.png


sabermembers:
  - name: Jeremy Doan 
    position: Saber Team Commander
    img: Doan, Jeremy 20202021.png
  - name: Jason Zhao
    position: Saber Team NCO
    img: Zhao, Jason 20202021.png

unarmedmembers:
  - name: Rachelle Soriano
    position: Unarmed Team Commander
    img: Soriano, Rachelle 20202021.png
  - name: Christopher Villalobos
    position: Unarmed Team NCO
    img: Villalobos, Christopher 20202021.png


academicmembers:
  - name: Raymond Sun
    position: Academic Team Officer
    img: Sun, Raymond 20202021.png
  - name: Kevin Zhao
    position: Academic Team NCO
    img: Zhao, Kevin 20202021.png
    
 
 
stellarmembers:
  - name: Rutva Mehta
    position: Stellar Xplorers Officer
    img: Mehta, Rutva 20202021.png
  - name: Carter Johnson
    position: Stellar Xplorers SNCO
    img: Johnson, Carter 20202021.jpg
  - name: Kaushik Vada
    position: Stellar Xplorers NCO
    img: Vada, Kaushik 20202021.jpg
  - name: Andrew Zhang
    position: Stellar Xplorers NCO
    img: Zhang, Andrew 20202021.jpg  
     
  
kittyhawkmembers:
  - name: Trenton Bien
    position: Kitty Hawk Officer
    img: Bien, Trenton 20202021.png
  - name: Britney Ton
    position: Kitty Hawk NCO
    img: Ton, Britney 20202021.png
  - name: Shruti Natala
    position: Kitty Hawk NCO
    img: Natala, Shruti 20202021.png
    
educationmembers:
  - name: Neel Kumar
    position: Education Officer
    img: Kumar, Neel 20202021.png
  - name: Mansi Sharma
    position: Education NCO
    img: Sharma, Mansi 20202021.png
    

staffmembers:
  - name: Christian Yoon
    position: Group Commander
    img: Yoon, Christian.jpg
    social:
      - title: envelope
        url: mailto:cky2003florida@gmail.com
  - name: Samantha Scotchlas
    position: Deputy Commander
    img: Scotchlas, Samantha.jpg
    social:
      - title: envelope
        url: mailto:samantha.scotchlas@gmail.com
  - name: Philip Sargent
    position: First Sergeant
    img: Sargent, Philip.JPG
    social:
      - title: envelope
        url: mailto:philipsargent005@gmail.com
  - name: Katherine Tat
    position: Operations Commander
    img: Tat, Katherine.jpg
    social:
      - title: envelope
        url: mailto:tkatherine2003@gmail.com
  - name: Ryan Ong
    position: Mission Support Commander
    img: Chad, Absolute.jpg
    social:
      - title: envelope
        url: mailto:r.ong40915@gmail.com
  - name: Mackenzie Trinh
    position: Plans and Programs
    img: Trinh, Mackenzie.JPG
    social:
      - title: envelope
        url: mailto:mackenzietrinh@gmail.com
  - name: Justin Bui
    position: Public Affairs Commander
    img: Bui, Justin.jpeg
    social:
      - title: envelope
        url: mailto:justin7354@gmail.com
  - name: Jacob Wong
    position: Logistics Commander
    img: Wong, Jacob.jpg
    social:
      - title: envelope
        url: mailto:jacwub1738@gmail.com
  - name: Derek Phan
    position: Teams Commander
    img: Phan, Derek.jpg
    social:
      - title: envelope
        url: mailto:derekphan2927@gmail.com

ypfmembers:
  - name: Jessica Tuey
    position: YPF Captain
    img: Tuey, Jessica 20202021.JPG
  - name: Sabella Ibinyopakaka
    position: YPF Co-Captain
    img: Ibinyopakaka, Sabella 20202021.JPG 

aptmembers:
  - name: Cassandra Portrey
    position: APT Commander
    img: Portrey, Cassandra 20202021.JPG
  - name: Isabella Canales
    position: APT NCO
    img: Canales, Isabella 20202021.jpg

cyberpatriotmembers:
  - name: Mikella Nuzen
    position: CyberPatriot Officer
    img: Nuzen, Mikella 20202021.JPG
  - name: Michael He
    position: CyberPatriot NCO
    img: He, Michael 20202021.JPG
 

# Clients information. Shown on Home and About pages.
sponsors:
  - name: iD Tech
    img: sponsor1.svg

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Scripps Ranch High School’s Air Force Junior Reserve Officer Training Corps (AFJROTC) CA-935th program has been the number 
one JROTC unit in the San Diego Unified School District for many years. We value hard-work, friendship, and achievement, pushing our 
cadets not only to be their best, but also to perform their best."

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "It's not what you have or what you know; it's what you do with your talent, skills, knowledge, and education that will determine your perfomance and give you the competitive edge!"
    author: MSgt. Toledo
    position: Aerospace Science Instructor - SRHS AFJROTC

prose:
  rooturl: '_posts'
  siteurl: 'https://ca-935.github.io'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "tag1"
              value: "tag1"
            - name: "tag2s"
              value: "tag2"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
