### GENERAL SETTINGS ###

# Site settings
title: CA-935th - Scripps Ranch HS AFJROTC
description: "Welcome to the page for the Scripps Ranch High School AFJROTC. CA-935th.com is run by cadets in our program and serves to showcase our events, 
cadets, and information about our corps."
baseurl: ""
url: "http://ca-935th.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
    limit: 9

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: https://github.com/CA-935
  - title: facebook
    url: https://www.facebook.com/srhspublicaffairs
  - title: snapchat-ghost
    url: https://www.snapchat.com/add/srhspa
  - title: youtube-play
    url: https://www.youtube.com/channel/UC13o8MjH8SXrb1QIAHcCEdA
  - title: instagram
    url: https://www.instagram.com/ca.935th

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - 10410 Treena Street
    - San Diego, CA 92131
#email: 
#tel: it's in the contact us page so dont put it here


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
#members:
#  - name: Mark Webber
#    position: CEO
#    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
#    img: team01.jpg
#    social:
#      - title: envelope #use for email address
#        url: mailto:name@domain.com
#      - title: twitter
#        url: http://twitter.com/handle

members:
  - name: Justin Bui
    position: Public Affairs Officer
    img: Bui, Justin.jpeg
    
 
  - name: Khushi Chaudhari
    position: Public Affairs NCO
    img: Chaudhari, Khushi2021.jpg
  - name: Sanjana Santhosh
    position: Public Affairs NCO
    img: Santhosh, Sanjana.jpg
    
  - name: Johann Welch
    position: Technology Officer
    img: Welch, Johann.jpg
    
  - name: Sahithi Lingampalli
    position: Technology NCO
    img: Lingampalli, Sahithi.png
  - name: Keshav Srinivasan
    position: Technology NCO
    img: Srinivasan, Keshav.jpg
    
    
alphamembers:
  - name: Katherine Tat
    position: Alpha Flight Commander
    img: alphacc1920.jpg
  - name: Patrick Ngo
    position: Alpha Flight Sergeant
    img: alphasgt1920.jpg
   
bravomembers:
  - name: Samantha Scotchlas
    position: Bravo Flight Commander
    img: bravocc1920.jpg
  - name: Marcus Velasquez
    position: Bravo Flight Sergeant
    img: bravosgt1920.jpg
    
charliemembers:
  - name: Thu Vu
    position: Charlie Flight Commander
    img: charliecc1920.jpg
  - name: Christina Nguyen
    position: Charlie Flight Sergeant
    img: charliesgt1920.jpg
    
deltamembers:
  - name: Christian Yoon
    position: Delta Flight Commander
    img: deltacc1920.jpg
  - name: Joshua Pagaduan
    position: Delta Flight Sergeant
    img: deltasgt1920.jpg
    
echomembers:
  - name: Philip Sargent
    position: Echo Flight Commander
    img: echocc1920.jpg
  - name: Rutva Mehta
    position: Echo Flight Sergeant
    img: echosgt1920.jpg    

foxtrotmembers:
  - name: Xavier dela Cruz
    position: Foxtrot Flight Commander
    img: foxtrotcc1920.jpg
  - name: Justin Nguyen
    position: Foxtrot Flight Sergeant
    img: foxtrotsgt1920.jpg
    
golfmembers:
  - name: Ryan Ong
    position: Golf Flight Commander
    img: golfcc1920.jpg
  - name: Rusell Lee
    position: Golf Flight Sergeant
    img: golfsgt1920.jpg
    
hotelmembers:
  - name: David Udom
    position: Hotel Flight Commander
    img: Udom, David.jpg
  - name: Tom Rufino
    position: Hotel Flight Sergeant
    img: Rufino, Tom.jpg

    
    

armedmembers:
  - name: EJ Buan
    position: Armed Team Commander
    img: ejarmedcc.jpg
  - name: Tom Rufino
    position: Armed Team NCO
    img: tomarmednco.jpg

cgmembers:
  - name: Derek Phan
    position: Color Guard Commander
    img: cgcc1920.jpg
  - name: Elijah Bautista
    position: Color Guard NCO
    img: cgsgt1920.jpg


flagdetailmembers:
  - name: Trenton Bien
    img: flagdetcc1920.jpg
    position: Flag Detail Commander
  - name: Vincent Dang
    position: Flag Detail NCO
    img: flagdetsgt1920.jpg


sabermembers:
  - name: Jeremy Doan 
    position: Saber Team Commander
    img: sfdtcc1920.jpg
  - name: Sabella Ibinyopakaka
    position: Saber Team NCO
    img: sfdtsgt1920.jpg

unarmedmembers:
  - name: Abel Hurtado
    position: Unarmed Team Commander
    img: ufdtcc1920.jpg
  - name: Rachelle Soriano
    position: Unarmed Team NCO
    img: ufdtsgt1920.jpg


academicmembers:
  - name: Raymond Sun
    position: Academic Team Officer
    img: Sun, Raymond.jpg
  - name: Vanessa Zhou
    position: Academic Team NCO
    img: Zhou, Vanessa.jpg
    
 
 
stellarmembers:
  - name: Marcus Velasquez
    position: Stellar Xplorers NCO
    img: 20192020stellarxsgt1.jpg
  - name: Rutva Mehta
    position: Stellar Xplorers NCO
    img: 20192020stellarxsgt2.jpg
     
  
kittyhawkmembers:
  - name: Tina Ton
    position: Kitty Hawk Officer
    img: tinakittyhawkcc.jpg
  - name: Alysia Roh
    position: Kitty Hawk NCO
    img: alysiakittyhawknco.jpg	
  - name: Samuel Chen
    position: Kitty Hawk NCO
    img: samuelkittyhawknco.jpg
    
educationmembers:
  - name: Harshil Thakur
    position: Education Officer
    img: educationcc1920.jpg
  - name: Neel Kumar
    position: Education NCO
    img: educationsgt1920.jpg


staffmembers:
  - name: Christian Yoon
    position: Group Commander
    img: Yoon, Christian.jpg
  - name: Samantha Scotchlas
    position: Deputy Commander
    img: Scotchlas, Samantha.jpg
  - name: Philip Sargent
    position: First Sergeant
    img: Sargent, Philip.JPG
  - name: Tat, Katherine 
    position: Operations Commander
    img: Tat, Katherine.jpg
  - name: Ryan Ong
    position: Mission Support Commander
    img: Chad, Absolute.jpg
  - name: Mackenzie Trinh
    position: Plans and Programs
    img: Trinh, Mackenzie.JPG
  - name: Justin Bui
    position: Public Affairs Commander
    img: Bui, Justin.jpeg
  - name: Jacob Wong
    position: Logistics Commander
    img: Wong, Jacob.jpg
  - name: Phan, Derek
    position: Teams Commander
    img: Phan, Derek.jpg

ypfmembers:
  - name: Mackenzie Trinh
    position: YPF Captain
    img: mackenzieypfccFix.jpg
  - name: Jessica Tuey
    position: YPF Co-Captain
    img: jessicaypfncoFix.jpg

aptmembers:
  - name: Nyssa Sais Montoya
    position: APT Commander
    img: aptcc1920.jpg
  - name: Cassandra Portrey
    position: APT NCO
    img: aptsgt1920.jpg

cyberpatriotmembers:
  - name: Mikella Nuzen
    position: CyberPatriot SNCO
    img: Nuzen, Mikella.jpg
  - name: Jake Lee
    position: CyberPatriot NCO
    img: Lee, Jake.jpg
  - name: Patrick Ngo
    position: CyberPatriot NCO
    img: Ngo, Patrick.jpg

# Clients information. Shown on Home and About pages.
sponsors:
  - name: iD Tech
    img: sponsor1.svg

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Scripps Ranch High School’s Air Force Junior Reserve Officer Training Corps (AFJROTC) CA-935th program has been the number 
one JROTC unit in the San Diego Unified School District for many years. We value hard-work, friendship, and achievement, pushing our 
cadets not only to be their best, but also to perform their best."

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "It's not what you have or what you know; it's what you do with your talent, skills, knowledge, and education that will determine your perfomance and give you the competitive edge!"
    author: MSgt. Toledo
    position: Aerospace Science Instructor - SRHS AFJROTC

prose:
  rooturl: '_posts'
  siteurl: 'https://ca-935.github.io'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "tag1"
              value: "tag1"
            - name: "tag2s"
              value: "tag2"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
